/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class CombatResources
    {
        public bool valid = false;

        internal CombatResources()
        {
            //Made for conditional structures
        }

        internal CombatResources(LostArkMessageReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt16();
            if(Unk0 <= 5)
            {
                for(var i = 0; i < Unk0; i++)
                {
                    Struct_580.Add(new Struct_580(reader));
                }
            }
        }

        public short Unk0 {get;}
        public List<Struct_580> Struct_580 {get;} = new List<Struct_580>();
    }
}