/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class EquipedItems
    {
        public bool valid = false;

        internal EquipedItems()
        {
            //Made for conditional structures
        }

        internal EquipedItems(LostArkMessageReader reader)
        {
            valid = true;
            Count = reader.ReadInt16();
            if (Count <= 30)
            {
                for (var i = 0; i < Count; i++)
                {
                    Items.Add(new EquipedItem(reader));
                }
            }
        }

        public short Count { get; }
        public List<EquipedItem> Items { get; } = new List<EquipedItem>();
    }
}