/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class EquipedItem
    {
        public bool valid = false;

        internal EquipedItem()
        {
            //Made for conditional structures
        }

        internal EquipedItem(LostArkMessageReader reader)
        {
            valid = true;
            Struct_362_0 = new Struct_362(reader);
            Id = reader.ReadInt32();
            Slot = reader.ReadInt16();
            Unk3 = reader.ReadInt16();
            Read2or8BBytesProcessed_4 = new Read2or8BBytesProcessed(reader);
        }

        public Struct_362 Struct_362_0 {get;} = new Struct_362();
        public int Id { get; }
        public short Slot { get; }
        public short Unk3 {get;}
        public Read2or8BBytesProcessed Read2or8BBytesProcessed_4 {get;} = new Read2or8BBytesProcessed();
    }
}