/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class PCStruct
    {
        public bool valid = false;

        internal PCStruct()
        {
            //Made for conditional structures
        }

        internal PCStruct(LostArkMessageReader reader)
        {
            valid = true;
            Unk0 = reader.ReadByte();
            Gear = new EquipedItems(reader);
            Unk2 = reader.ReadInt32();
            Unk3 = reader.ReadByte();
            Unk4 = reader.ReadInt16();
            Unk5 = reader.ReadBytes(25);
            Unk6 = reader.ReadInt64();
            Unk7 = reader.ReadByte();
            SkillSet = new SkillSet(reader);
            StatusEffects = new StatusEffects(reader);
            Unk10 = reader.ReadByte();
            Position = reader.ReadInt64();
            Unk12 = reader.ReadInt32();
            Heading = reader.ReadInt16();
            Unk14 = reader.ReadByte();
            GuildName = new NameString(reader);
            Unk16 = reader.ReadByte();
            Unk17 = reader.ReadByte();
            CombatResources = new CombatResources(reader);
            Unk19 = reader.ReadInt32();
            ClassId = reader.ReadInt16();
            Unk21 = reader.ReadInt32();
            Unk22 = reader.ReadByte();
            if(Unk22 == 1)
            {
                Unk22_0 = reader.ReadBytes(12);
            }
            Unk23 = reader.ReadInt32();
            Level = reader.ReadInt16();
            PetId = reader.ReadInt32();
            SkillRunes = new SkillRunes(reader);
            EquipedTradeItems = new EquipedTradeItems(reader);
            Unk28 = reader.ReadInt32();
            Unk29 = reader.ReadByte();
            Id = reader.ReadInt64();
            Unk31 = reader.ReadByte();
            Unk32 = reader.ReadInt16();
            Name = new NameString(reader);
            Unk34 = reader.ReadInt32();
            Struct_69_36 = new Struct_69(reader);
            Unk36 = reader.ReadByte();
            Struct_44_38 = new Struct_44(reader);
            Unk38 = reader.ReadInt32();
            Unk39 = reader.ReadByte();
            Unk40 = reader.ReadInt32();
            Unk41 = reader.ReadByte();
        }

        public byte Unk0 {get;}
        public EquipedItems Gear { get; } = new EquipedItems();
        public int Unk2 {get;}
        public byte Unk3 {get;}
        public short Unk4 {get;}
        public byte[] Unk5 {get;}
        public long Unk6 {get;}
        public byte Unk7 {get;}
        public SkillSet SkillSet { get; } = new SkillSet();
        public StatusEffects StatusEffects { get; } = new StatusEffects();
        public byte Unk10 {get;}
        public long Position { get; }
        public int Unk12 {get;}
        public short Heading { get; }
        public byte Unk14 {get;}
        public NameString GuildName { get; } = new NameString();
        public byte Unk16 {get;}
        public byte Unk17 {get;}
        public CombatResources CombatResources { get; } = new CombatResources();
        public int Unk19 {get;}
        public short ClassId { get; }
        public int Unk21 {get;}
        public byte Unk22 {get;}
        public byte[] Unk22_0 {get;}
        public int Unk23 {get;}
        public short Level { get; }
        public int PetId { get; }
        public SkillRunes SkillRunes { get; } = new SkillRunes();
        public EquipedTradeItems EquipedTradeItems { get; } = new EquipedTradeItems();
        public int Unk28 {get;}
        public byte Unk29 {get;}
        public long Id { get; }
        public byte Unk31 {get;}
        public short Unk32 {get;}
        public NameString Name { get; } = new NameString();
        public int Unk34 {get;}
        public Struct_69 Struct_69_36 {get;} = new Struct_69();
        public byte Unk36 {get;}
        public Struct_44 Struct_44_38 {get;} = new Struct_44();
        public int Unk38 {get;}
        public byte Unk39 {get;}
        public int Unk40 {get;}
        public byte Unk41 {get;}
    }
}