/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class ReadNBytesInt64
    {
        public bool valid = false;
        internal ReadNBytesInt64()
        {
            //Made for conditional structures
        }

        internal ReadNBytesInt64(LostArkMessageReader reader)
        {
            valid = true;
        }

    }
}