/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class SkillDamageEvent
    {
        public bool valid = false;

        internal SkillDamageEvent()
        {
            //Made for conditional structures
        }

        internal SkillDamageEvent(LostArkMessageReader reader)
        {
            valid = true;
            Damage = new ReadNBytesInt64(reader);
            Unk1 = reader.ReadByte();
            if(Unk1 == 1)
            {
                Unk1_0 = reader.ReadByte();
            }
            Unk2 = reader.ReadByte();
            Unk3 = reader.ReadInt16();
            Modifier = reader.ReadByte();
            Health = new ReadNBytesInt64(reader);
            InitialHealth = new ReadNBytesInt64(reader);
            Target = reader.ReadInt64();
        }

        public ReadNBytesInt64 Damage { get; } = new ReadNBytesInt64();
        public byte Unk1 {get;}
        public byte Unk1_0 {get;}
        public byte Unk2 {get;}
        public short Unk3 {get;}
        public byte Modifier { get; }
        public ReadNBytesInt64 Health { get; } = new ReadNBytesInt64();
        public ReadNBytesInt64 InitialHealth { get; } = new ReadNBytesInt64();
        public long Target { get; }
    }
}