/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class SkillSet
    {
        public bool valid = false;

        internal SkillSet()
        {
            //Made for conditional structures
        }

        internal SkillSet(LostArkMessageReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt16();
            if (Unk0 <= 200)
            {
                for (var i = 0; i < Unk0; i++)
                {
                    Skills.Add(new Skill(reader));
                }
            }
        }

        public short Unk0 {get;}

        public class Skill
        {
            public bool valid = false;

            internal Skill()
            {
                //Made for conditional structures
            }

            internal Skill(LostArkMessageReader reader)
            {
                valid = true;
                CombatEffects = new CombatEffects(reader);
                Id = reader.ReadInt32();
            }

            public CombatEffects CombatEffects { get; } = new CombatEffects();
            public int Id { get; }
        }

        public List<Skill> Skills { get; } = new List<Skill>();
    }
}