/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class SkillDamageEvents
    {
        public bool valid = false;

        internal SkillDamageEvents()
        {
            //Made for conditional structures
        }

        internal SkillDamageEvents(LostArkMessageReader reader)
        {
            valid = true;
            Count = reader.ReadInt16();
            if (Count <= 50)
            {
                for (var i = 0; i < Count; i++)
                {
                    SkillDamageEvent.Add(new SkillDamageEvent(reader));
                }
            }
        }

        public short Count { get; }
        public List<SkillDamageEvent> SkillDamageEvent { get; } = new List<SkillDamageEvent>();
    }
}