/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class Struct_435
    {
        public bool valid = false;
        internal Struct_435()
        {
            //Made for conditional structures
        }

        internal Struct_435(LostArkMessageReader reader)
        {
            valid = true;
            Unk0 = reader.ReadByte();
            Unk1 = reader.ReadInt32();
            Unk2 = reader.ReadInt32();
            Unk3 = reader.ReadInt32();
            Unk4 = reader.ReadInt32();
            Unk5 = reader.ReadInt32();
            Unk6 = reader.ReadInt32();
            Struct_468_7 = new Struct_468(reader);
        }

        public byte Unk0 {get;}
        public int Unk1 {get;}
        public int Unk2 {get;}
        public int Unk3 {get;}
        public int Unk4 {get;}
        public int Unk5 {get;}
        public int Unk6 {get;}
        public Struct_468 Struct_468_7 {get;} = new Struct_468();
    }
}