/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class Struct_580
    {
        public bool valid = false;
        internal Struct_580()
        {
            //Made for conditional structures
        }

        internal Struct_580(LostArkMessageReader reader)
        {
            valid = true;
            Unk0 = reader.ReadByte();
            Unk1 = reader.ReadInt16();
            ReadNBytesInt64_2 = new ReadNBytesInt64(reader);
            Unk3 = reader.ReadInt64();
            Unk4 = reader.ReadByte();
            Unk5 = reader.ReadByte();
            ReadNBytesInt64_6 = new ReadNBytesInt64(reader);
        }

        public byte Unk0 {get;}
        public short Unk1 {get;}
        public ReadNBytesInt64 ReadNBytesInt64_2 {get;} = new ReadNBytesInt64();
        public long Unk3 {get;}
        public byte Unk4 {get;}
        public byte Unk5 {get;}
        public ReadNBytesInt64 ReadNBytesInt64_6 {get;} = new ReadNBytesInt64();
    }
}