/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class Struct_340
    {
        public bool valid = false;
        internal Struct_340()
        {
            //Made for conditional structures
        }

        internal Struct_340(LostArkMessageReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt16();
            if(Unk0 <= 50)
            {
                for(var i = 0; i < Unk0; i++)
                {
                    Struct_595.Add(new Struct_595(reader));
                }
            }
        }

        public short Unk0 {get;}
        public List<Struct_595> Struct_595 {get;} = new List<Struct_595>();
    }
}