/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class Struct_601
    {
        public bool valid = false;
        internal Struct_601()
        {
            //Made for conditional structures
        }

        internal Struct_601(LostArkMessageReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt32();
            Unk1 = reader.ReadInt32();
            Read2or8BBytesProcessed_2 = new Read2or8BBytesProcessed(reader);
            Unk3 = reader.ReadInt32();
            Unk4 = reader.ReadInt64();
            Unk5 = reader.ReadByte();
            if(Unk5 == 1)
            {
                Unk5_0 = reader.ReadInt64();
            }
            Unk6 = reader.ReadByte();
            Unk7 = reader.ReadInt64();
            Unk8 = reader.ReadByte();
            if(Unk8 == 1)
            {
                Unk8_0 = reader.ReadBytes(16);
            }
            Struct_355_11 = new Struct_355(reader);
            Unk10 = reader.ReadByte();
        }

        public int Unk0 {get;}
        public int Unk1 {get;}
        public Read2or8BBytesProcessed Read2or8BBytesProcessed_2 {get;} = new Read2or8BBytesProcessed();
        public int Unk3 {get;}
        public long Unk4 {get;}
        public byte Unk5 {get;}
        public long Unk5_0 {get;}
        public byte Unk6 {get;}
        public long Unk7 {get;}
        public byte Unk8 {get;}
        public byte[] Unk8_0 {get;}
        public Struct_355 Struct_355_11 {get;} = new Struct_355();
        public byte Unk10 {get;}
    }
}