/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class Struct_21
    {
        public bool valid = false;
        internal Struct_21()
        {
            //Made for conditional structures
        }

        internal Struct_21(LostArkMessageReader reader)
        {
            valid = true;
            Unk0 = reader.ReadInt16();
            if(Unk0 <= 64)
            {
                for(var i = 0; i < Unk0; i++)
                {
                    sub_Unk0_0.Add(new sub_Unk0(reader));
                }
            }
        }

        public short Unk0 {get;}
        public class sub_Unk0
        {
            public bool valid = false;
            internal sub_Unk0()
            {
                //Made for conditional structures
            }
            internal sub_Unk0(LostArkMessageReader reader)
            {
                valid = true;
                Struct_449_0 = new Struct_449(reader);
                Struct_455_1 = new Struct_455(reader);
                Struct_460_2 = new Struct_460(reader);
            }

            public Struct_449 Struct_449_0 {get;} = new Struct_449();
            public Struct_455 Struct_455_1 {get;} = new Struct_455();
            public Struct_460 Struct_460_2 {get;} = new Struct_460();
        }
        public List<sub_Unk0> sub_Unk0_0 {get;} = new List<sub_Unk0>();
    }
}