/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Structures
{
    public class Struct_595
    {
        public bool valid = false;
        internal Struct_595()
        {
            //Made for conditional structures
        }

        internal Struct_595(LostArkMessageReader reader)
        {
            valid = true;
            Struct_435_0 = new Struct_435(reader);
            Unk1 = reader.ReadByte();
            Unk2 = reader.ReadInt64();
            Unk3 = reader.ReadInt16();
            Struct_596_4 = new SkillDamageEvent(reader);
            Unk5 = reader.ReadInt16();
            Unk6 = reader.ReadInt16();
            Unk7 = reader.ReadInt64();
            Unk8 = reader.ReadInt64();
        }

        public Struct_435 Struct_435_0 {get;} = new Struct_435();
        public byte Unk1 {get;}
        public long Unk2 {get;}
        public short Unk3 {get;}
        public SkillDamageEvent Struct_596_4 { get; } = new SkillDamageEvent();
        public short Unk5 {get;}
        public short Unk6 {get;}
        public long Unk7 {get;}
        public long Unk8 {get;}
    }
}