/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Structures;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Definitions
{
    public class PKTDeathNotify : ParsedMessage
    {
        public PKTDeathNotify(LostArkMessageReader reader) : base(reader)
        {
            Unk0 = reader.ReadByte();
            if(Unk0 == 1)
            {
                Unk0_0 = reader.ReadByte();
            }
            Unk1 = reader.ReadInt32();
            Unk2 = reader.ReadByte();
            if(Unk2 == 1)
            {
                Unk2_0 = reader.ReadByte();
            }
            Unk3 = reader.ReadInt16();
            Unk4 = reader.ReadInt64();
            Unk5 = reader.ReadByte();
            if(Unk5 == 1)
            {
                Unk5_0 = reader.ReadByte();
            }
            Unk6 = reader.ReadInt64();
            Unk7 = reader.ReadInt64();
            Unk8 = reader.ReadByte();
        }

        public byte Unk0 {get;}
        public byte Unk0_0 {get;}
        public int Unk1 {get;}
        public byte Unk2 {get;}
        public byte Unk2_0 {get;}
        public short Unk3 {get;}
        public long Unk4 {get;}
        public byte Unk5 {get;}
        public byte Unk5_0 {get;}
        public long Unk6 {get;}
        public long Unk7 {get;}
        public byte Unk8 {get;}
    }
}