/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Structures;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Definitions
{
    public class PKTInitPC : ParsedMessage
    {
        public PKTInitPC(LostArkMessageReader reader) : base(reader)
        {
            Unk0 = reader.ReadByte();
            Unk1 = reader.ReadInt32();
            Unk2 = reader.ReadByte();
            Unk3 = reader.ReadByte();
            Unk4 = reader.ReadByte();
            Unk5 = reader.ReadInt16();
            Unk6 = reader.ReadByte();
            Unk7 = reader.ReadInt32();
            Unk8 = reader.ReadInt64();
            Unk9 = reader.ReadByte();
            Unk10 = reader.ReadByte();
            Unk11 = reader.ReadInt32();
            Unk12 = reader.ReadInt16();
            Unk13 = reader.ReadInt32();
            Unk14 = reader.ReadInt32();
            Unk15 = reader.ReadInt32();
            Unk16 = reader.ReadInt32();
            Unk17 = reader.ReadByte();
            Unk18 = reader.ReadInt64();
            Unk19 = reader.ReadInt32();
            Struct_268_20 = new Struct_268(reader);
            Unk21 = reader.ReadByte();
            Unk22 = reader.ReadByte();
            Unk23 = reader.ReadByte();
            Struct_273_24 = new Struct_273(reader);
            Unk25 = reader.ReadByte();
            Unk26 = reader.ReadInt16();
            Struct_44_27 = new Struct_44(reader);
            Unk28 = reader.ReadBytes(112);
            Name = new NameString(reader);
            Unk30 = reader.ReadInt16();
            Unk31 = reader.ReadInt32();
            Struct_74_32 = new Struct_74(reader);
            Unk33 = reader.ReadByte();
            Unk34 = reader.ReadInt64();
            Unk35 = reader.ReadByte();
            Struct_394_36 = new Struct_394(reader);
            Struct_395_37 = new Struct_395(reader);
            Unk38 = reader.ReadByte();
            Unk39 = reader.ReadByte();
            Unk40 = reader.ReadInt64();
            Unk41 = reader.ReadBytes(25);
            Unk42 = reader.ReadByte();
            if(Unk42 == 1)
            {
                Unk42_0 = reader.ReadInt32();
            }
            Unk43 = reader.ReadInt16();
            Unk44 = reader.ReadByte();
            Struct_354_46 = new StatusEffects(reader);
            Unk46 = reader.ReadInt16();
            Unk47 = reader.ReadByte();
            Struct_316_49 = new CombatResources(reader);
            Unk49 = reader.ReadByte();
            Unk50 = reader.ReadByte();
            Unk51 = reader.ReadByte();
            Unk52 = reader.ReadInt32();
        }

        public byte Unk0 {get;}
        public int Unk1 {get;}
        public byte Unk2 {get;}
        public byte Unk3 {get;}
        public byte Unk4 {get;}
        public short Unk5 {get;}
        public byte Unk6 {get;}
        public int Unk7 {get;}
        public long Unk8 {get;}
        public byte Unk9 {get;}
        public byte Unk10 {get;}
        public int Unk11 {get;}
        public short Unk12 {get;}
        public int Unk13 {get;}
        public int Unk14 {get;}
        public int Unk15 {get;}
        public int Unk16 {get;}
        public byte Unk17 {get;}
        public long Unk18 {get;}
        public int Unk19 {get;}
        public Struct_268 Struct_268_20 {get;} = new Struct_268();
        public byte Unk21 {get;}
        public byte Unk22 {get;}
        public byte Unk23 {get;}
        public Struct_273 Struct_273_24 {get;} = new Struct_273();
        public byte Unk25 {get;}
        public short Unk26 {get;}
        public Struct_44 Struct_44_27 {get;} = new Struct_44();
        public byte[] Unk28 {get;}
        public NameString Name { get; } = new NameString();
        public short Unk30 {get;}
        public int Unk31 {get;}
        public Struct_74 Struct_74_32 {get;} = new Struct_74();
        public byte Unk33 {get;}
        public long Unk34 {get;}
        public byte Unk35 {get;}
        public Struct_394 Struct_394_36 {get;} = new Struct_394();
        public Struct_395 Struct_395_37 {get;} = new Struct_395();
        public byte Unk38 {get;}
        public byte Unk39 {get;}
        public long Unk40 {get;}
        public byte[] Unk41 {get;}
        public byte Unk42 {get;}
        public int Unk42_0 {get;}
        public short Unk43 {get;}
        public byte Unk44 {get;}
        public StatusEffects Struct_354_46 { get; } = new StatusEffects();
        public short Unk46 {get;}
        public byte Unk47 {get;}
        public CombatResources Struct_316_49 { get; } = new CombatResources();
        public byte Unk49 {get;}
        public byte Unk50 {get;}
        public byte Unk51 {get;}
        public int Unk52 {get;}
    }
}