/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Structures;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Definitions
{
    public class PKTInitEnv : ParsedMessage
    {
        public PKTInitEnv(LostArkMessageReader reader) : base(reader)
        {
            Unk0 = reader.ReadInt32();
            Unk1 = reader.ReadInt64();
            Read2or8BBytesProcessed_2 = new Read2or8BBytesProcessed(reader);
            Unk3 = reader.ReadInt32();
            Struct_460_4 = new Struct_460(reader);
            Unk5 = reader.ReadByte();
            PlayerId = reader.ReadInt64();
            Struct_21_7 = new Struct_21(reader);
        }

        public int Unk0 {get;}
        public long Unk1 {get;}
        public Read2or8BBytesProcessed Read2or8BBytesProcessed_2 {get;} = new Read2or8BBytesProcessed();
        public int Unk3 {get;}
        public Struct_460 Struct_460_4 {get;} = new Struct_460();
        public byte Unk5 {get;}
        public long PlayerId { get; }
        public Struct_21 Struct_21_7 {get;} = new Struct_21();
    }
}