/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Structures;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Definitions
{
    public class PKTNewNpc : ParsedMessage
    {
        public PKTNewNpc(LostArkMessageReader reader) : base(reader)
        {
            Unk0 = reader.ReadByte();
            Unk1 = reader.ReadByte();
            if(Unk1 == 1)
            {
                Unk1_0 = reader.ReadInt64();
            }
            Unk2 = reader.ReadByte();
            if(Unk2 == 1)
            {
                Unk2_0 = reader.ReadByte();
            }

            NpcStruct = new NpcStruct(reader);
        }

        public byte Unk0 {get;}
        public byte Unk1 {get;}
        public long Unk1_0 {get;}
        public byte Unk2 {get;}
        public byte Unk2_0 {get;}
        public NpcStruct NpcStruct { get; } = new NpcStruct();
    }
}