/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Structures;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Definitions
{
    public class PKTNewPC : ParsedMessage
    {
        public PKTNewPC(LostArkMessageReader reader) : base(reader)
        {
            Unk0 = reader.ReadByte();
            Unk1 = reader.ReadByte();
            if(Unk1 == 1)
            {
                Unk1_0 = reader.ReadInt32();
            }
            Unk2 = reader.ReadByte();
            if(Unk2 == 1)
            {
                Struct_613_0 = new Struct_613(reader);
            }
            Unk3 = reader.ReadByte();
            if(Unk3 == 1)
            {
                Unk3_0 = reader.ReadBytes(20);
            }

            PcStruct = new PCStruct(reader);
            Unk5 = reader.ReadByte();
            Unk6 = reader.ReadByte();
            if(Unk6 == 1)
            {
                Unk6_0 = reader.ReadBytes(12);
            }
        }

        public byte Unk0 {get;}
        public byte Unk1 {get;}
        public int Unk1_0 {get;}
        public byte Unk2 {get;}
        public Struct_613 Struct_613_0 {get;} = new Struct_613();
        public byte Unk3 {get;}
        public byte[] Unk3_0 {get;}
        public PCStruct PcStruct { get; } = new PCStruct();
        public byte Unk5 {get;}
        public byte Unk6 {get;}
        public byte[] Unk6_0 {get;}
    }
}