/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Structures;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Definitions
{
    public class PKTPartyStatusEffectAddNotify : ParsedMessage
    {
        public PKTPartyStatusEffectAddNotify(LostArkMessageReader reader) : base(reader)
        {
            Unk0 = reader.ReadByte();
            Struct_354_1 = new StatusEffects(reader);
            Unk2 = reader.ReadInt64();
            Unk3 = reader.ReadInt64();
        }

        public byte Unk0 {get;}
        public StatusEffects Struct_354_1 { get; } = new StatusEffects();
        public long Unk2 {get;}
        public long Unk3 {get;}
    }
}