/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Structures;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Definitions
{
    public class PKTPartyStatusEffectRemoveNotify : ParsedMessage
    {
        public PKTPartyStatusEffectRemoveNotify(LostArkMessageReader reader) : base(reader)
        {
            Struct_98_0 = new Struct_98(reader);
            Unk1 = reader.ReadInt64();
            Unk2 = reader.ReadByte();
        }

        public Struct_98 Struct_98_0 {get;} = new Struct_98();
        public long Unk1 {get;}
        public byte Unk2 {get;}
    }
}