/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Structures;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Definitions
{
    public class PKTStatusEffectRemoveNotify : ParsedMessage
    {
        public PKTStatusEffectRemoveNotify(LostArkMessageReader reader) : base(reader)
        {
            Unk0 = reader.ReadByte();
            Unk1 = reader.ReadInt64();
            Struct_98_2 = new Struct_98(reader);
        }

        public byte Unk0 {get;}
        public long Unk1 {get;}
        public Struct_98 Struct_98_2 {get;} = new Struct_98();
    }
}