/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Structures;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Definitions
{
    public class PKTSkillDamageNotify : ParsedMessage
    {
        public PKTSkillDamageNotify(LostArkMessageReader reader) : base(reader)
        {
            SkillId = reader.ReadInt32();
            Source = reader.ReadInt64();
            SkillEffect = reader.ReadInt32();
            Unk3 = reader.ReadByte();
            SkillDamageEvents = new SkillDamageEvents(reader);
        }

        public int SkillId { get; }
        public long Source { get; }
        public int SkillEffect { get; }
        public byte Unk3 {get;}
        public SkillDamageEvents SkillDamageEvents { get; } = new SkillDamageEvents();
    }
}