/*
 * This file has been Auto Generated, Please do not edit.
 * If you need changes, follow the instructions written in the readme.md
 *
 * Generated by Herysia.
 */

using System;
using System.Collections.Generic;
using LostArk.Game.Messages.Services;
using LostArk.Game.Messages.Structures;
using LostArk.Game.Messages.Types;

namespace LostArk.Game.Messages.Definitions
{
    public class PKTSkillDamageAbnormalMoveNotify : ParsedMessage
    {
        public PKTSkillDamageAbnormalMoveNotify(LostArkMessageReader reader) : base(reader)
        {
            Unk0 = reader.ReadInt64();
            Unk1 = reader.ReadInt32();
            Unk2 = reader.ReadByte();
            Struct_340_3 = new Struct_340(reader);
            Unk4 = reader.ReadInt32();
        }

        public long Unk0 {get;}
        public int Unk1 {get;}
        public byte Unk2 {get;}
        public Struct_340 Struct_340_3 {get;} = new Struct_340();
        public int Unk4 {get;}
    }
}